%% ANN BAYESIAN OPTIMIZATION WITH 5-FOLD CROSS-VALIDATION
% Optimize ONLY ANN hyperparameters:
%   1) Learning rate
%   2) Number of neurons per hidden layer
%   3) Number of hidden layers
%
% Selection criterion: minimum mean 5-fold validation RMSE.
% Independent testing data are NOT used during Bayesian optimization.

clear; clc; close all;
tTotal = tic;

%% EXPORT COMMAND WINDOW TO TEXT FILE
commandWindowFile = 'ANN_N_S_BayesianOptimization_5Fold_CommandWindow.txt';
if exist(commandWindowFile,'file')
    delete(commandWindowFile);
end
diary(commandWindowFile);
cleanupDiary = onCleanup(@() diary('off'));
fprintf('Command Window log started: %s\n', datestr(now,'yyyy-mm-dd HH:MM:SS'));

%% 1) SETTINGS
trainFile = 'N_S_Training_DATASET_75.xlsx';
testFile  = 'N_S_Testing_DATASET_25.xlsx';

K = 5;
fixedSeed = 1;

% ===== Bayesian Optimization =====
maxObjectiveEvaluations = 60;

% Search ranges
learningRateRange = [1e-5 5e-4];
numNeuronsRange   = [8 128];
hiddenLayersRange = [2 5];

% ===== Fixed ANN Settings =====
numIter = 100000;

lambda_data_total = 0.005;
lambda_reg = 1e-7;

lossTol = 1e-5;
checkEvery = 5000;
minIterCheck = 10000;

outDir = 'Results_ANN_N_S_BayesianOptimization_5Fold';
if ~exist(outDir,'dir')
    mkdir(outDir);
end

excelFile = fullfile(outDir,'ANN_N_S_BayesianOptimization_5Fold_Results.xlsx');
matFile   = fullfile(outDir,'ANN_N_S_BayesianOptimization_5Fold_Results.mat');

rng(fixedSeed,'twister');

try
    gpuDevice([]);
catch
end

%% 2) LOAD DATA
Tr = readtable(trainFile,'VariableNamingRule','preserve');
Te = readtable(testFile ,'VariableNamingRule','preserve');

Tr.Properties.VariableNames = matlab.lang.makeValidName( ...
    strtrim(Tr.Properties.VariableNames));

Te.Properties.VariableNames = matlab.lang.makeValidName( ...
    strtrim(Te.Properties.VariableNames));

X = [Tr.D Tr.t Tr.fy Tr.fc Tr.L_D];
y = Tr.N;

Xtest = [Te.D Te.t Te.fy Te.fc Te.L_D];
ytest = Te.N;

n = size(X,1);
nTest = size(Xtest,1);

% Fixed folds for fair comparison among Bayesian trials
rng(fixedSeed,'twister');
cv = cvpartition(n,'KFold',K);

fprintf('\n====================================================\n');
fprintf('ANN BAYESIAN OPTIMIZATION + %d-FOLD CV\n',K);
fprintf('Maximum Bayesian evaluations = %d\n',maxObjectiveEvaluations);
fprintf('Testing set is excluded from optimization.\n');
fprintf('====================================================\n');

%% 3) BAYESIAN SEARCH SPACE
optimVars = [
    optimizableVariable('LearningRate',learningRateRange, ...
        'Transform','log')

    optimizableVariable('NumNeurons',numNeuronsRange, ...
        'Type','integer')

    optimizableVariable('HiddenLayers',hiddenLayersRange, ...
        'Type','integer')
];

%% 4) BAYESIAN OPTIMIZATION
objectiveFcn = @(T) annCVObjective( ...
    T, X, y, cv, K, fixedSeed, numIter, ...
    lambda_data_total, lambda_reg, ...
    lossTol, checkEvery, minIterCheck);

bayesResults = bayesopt( ...
    objectiveFcn, ...
    optimVars, ...
    'MaxObjectiveEvaluations',maxObjectiveEvaluations, ...
    'IsObjectiveDeterministic',true, ...
    'AcquisitionFunctionName','expected-improvement-plus', ...
    'UseParallel',false, ...
    'Verbose',1, ...
    'PlotFcn',[]);

%% 5) BEST HYPERPARAMETERS
% Use the best OBSERVED objective point. This is compatible with MATLAB
% versions that do not provide bestPointByMinObjective().
bestPoint = bayesResults.XAtMinObjective;

bestLearningRate = bestPoint.LearningRate;
bestNumNeurons   = bestPoint.NumNeurons;
bestHiddenLayers = bestPoint.HiddenLayers;

bestCV_RMSE = bayesResults.MinObjective;

fprintf('\n================ BEST BAYESIAN RESULT ================\n');
fprintf('Hidden layers = %d\n',bestHiddenLayers);
fprintf('Neurons       = %d\n',bestNumNeurons);
fprintf('Learning rate = %.6e\n',bestLearningRate);
fprintf('Best mean validation RMSE = %.4f kN\n',bestCV_RMSE);

%% 6) RETRAIN BEST HYPERPARAMETERS ON EACH OF THE 5 FOLDS
bestFoldModels = cell(K,1);
bestFoldMuX = cell(K,1);
bestFoldStdX = cell(K,1);
bestFoldMuy = nan(K,1);
bestFoldStdy = nan(K,1);

bestFoldMetrics = nan(K,7);
bestFoldStopIteration = nan(K,1);
bestFoldTrainingTime = nan(K,1);

for fold = 1:K

    idxTr = training(cv,fold);
    idxVa = test(cv,fold);

    Xtr = X(idxTr,:);
    ytr = y(idxTr);

    Xva = X(idxVa,:);
    yva = y(idxVa);

    muX = mean(Xtr,1);
    stdX = std(Xtr,0,1);
    stdX(stdX==0) = 1;

    muy = mean(ytr);
    stdy = std(ytr);
    if stdy==0
        stdy = 1;
    end

    xTr = dlarray(((Xtr-muX)./stdX)','CB');
    yTr = dlarray(((ytr-muy)./stdy)','CB');
    xVa = dlarray(((Xva-muX)./stdX)','CB');

    rng(fixedSeed + 10000 + fold,'twister');

    net = buildANN(bestHiddenLayers,bestNumNeurons);

    trailingAvg = [];
    trailingAvgSq = [];
    lossHistory = nan(numIter,1);

    stopIteration = numIter;

    tFold = tic;

    for it = 1:numIter

        [loss,grad] = dlfeval( ...
            @lossFun, ...
            net, ...
            xTr, ...
            yTr, ...
            lambda_data_total, ...
            lambda_reg);

        [net,trailingAvg,trailingAvgSq] = adamupdate( ...
            net, ...
            grad, ...
            trailingAvg, ...
            trailingAvgSq, ...
            it, ...
            bestLearningRate);

        lossHistory(it) = gather(extractdata(loss));

        if mod(it,checkEvery)==0 && it>=minIterCheck

            change = abs( ...
                lossHistory(it) - ...
                lossHistory(it-checkEvery));

            if change < lossTol
                stopIteration = it;
                break
            end
        end
    end

    bestFoldTrainingTime(fold) = toc(tFold);
    bestFoldStopIteration(fold) = stopIteration;

    predVa = predictReal(net,xVa,muy,stdy);

    bestFoldMetrics(fold,:) = calcMetrics(yva,predVa);

    bestFoldModels{fold} = net;
    bestFoldMuX{fold} = muX;
    bestFoldStdX{fold} = stdX;
    bestFoldMuy(fold) = muy;
    bestFoldStdy(fold) = stdy;

    fprintf( ...
        'Fold %d/%d | Iter=%d | Val RMSE=%.3f | R2=%.5f\n', ...
        fold, ...
        K, ...
        stopIteration, ...
        bestFoldMetrics(fold,3), ...
        bestFoldMetrics(fold,4));
end

%% 7) INDEPENDENT TESTING
testPredByFold = nan(nTest,K);

for fold = 1:K

    xTest = dlarray( ...
        ((Xtest-bestFoldMuX{fold})./bestFoldStdX{fold})', ...
        'CB');

    testPredByFold(:,fold) = predictReal( ...
        bestFoldModels{fold}, ...
        xTest, ...
        bestFoldMuy(fold), ...
        bestFoldStdy(fold));
end

% Ensemble prediction of five independently trained fold models
testPred = mean(testPredByFold,2);

testMetrics = calcMetrics(ytest,testPred);

fprintf('\n================ INDEPENDENT TESTING ================\n');
fprintf('MAE  = %.3f kN\n',testMetrics(1));
fprintf('MSE  = %.3f kN^2\n',testMetrics(2));
fprintf('RMSE = %.3f kN\n',testMetrics(3));
fprintf('R2   = %.5f\n',testMetrics(4));
fprintf('A20  = %.2f %%\n',testMetrics(5));

%% 8) EXPORT BAYESIAN OPTIMIZATION HISTORY
BayesHistory = bayesResults.XTrace;

BayesHistory.Objective = bayesResults.ObjectiveTrace;

% Sort by objective, best first
BayesHistory = sortrows(BayesHistory,'Objective','ascend');

BestResult = table( ...
    bestHiddenLayers, ...
    bestNumNeurons, ...
    bestLearningRate, ...
    bestCV_RMSE, ...
    mean(bestFoldMetrics(:,1)), ...
    mean(bestFoldMetrics(:,2)), ...
    mean(bestFoldMetrics(:,3)), ...
    std(bestFoldMetrics(:,3)), ...
    mean(bestFoldMetrics(:,4)), ...
    std(bestFoldMetrics(:,4)), ...
    mean(bestFoldMetrics(:,5)), ...
    testMetrics(1), ...
    testMetrics(2), ...
    testMetrics(3), ...
    testMetrics(4), ...
    testMetrics(5), ...
    'VariableNames',{ ...
    'HiddenLayers', ...
    'NumNeurons', ...
    'LearningRate', ...
    'Bayes_MinObjective_RMSE', ...
    'CV_MAE_Mean', ...
    'CV_MSE_Mean', ...
    'CV_RMSE_Mean', ...
    'CV_RMSE_SD', ...
    'CV_R2_Mean', ...
    'CV_R2_SD', ...
    'CV_A20_Mean', ...
    'Testing_MAE', ...
    'Testing_MSE', ...
    'Testing_RMSE', ...
    'Testing_R2', ...
    'Testing_A20'});

FoldMetrics = table( ...
    (1:K)', ...
    bestFoldMetrics(:,1), ...
    bestFoldMetrics(:,2), ...
    bestFoldMetrics(:,3), ...
    bestFoldMetrics(:,4), ...
    bestFoldMetrics(:,5), ...
    bestFoldMetrics(:,6), ...
    bestFoldMetrics(:,7), ...
    bestFoldStopIteration, ...
    bestFoldTrainingTime, ...
    'VariableNames',{ ...
    'Fold', ...
    'MAE', ...
    'MSE', ...
    'RMSE', ...
    'R2', ...
    'A20_index', ...
    'MeanRatio', ...
    'SDRatio', ...
    'StopIteration', ...
    'TrainingTime_seconds'});

TestingPredictions = table( ...
    (1:nTest)', ...
    Xtest(:,1), ...
    Xtest(:,2), ...
    Xtest(:,3), ...
    Xtest(:,4), ...
    Xtest(:,5), ...
    ytest, ...
    testPred, ...
    testPred-ytest, ...
    testPred./ytest, ...
    'VariableNames',{ ...
    'Sample_ID', ...
    'D', ...
    't', ...
    'Fy', ...
    'Fc', ...
    'L_D', ...
    'N_exp', ...
    'N_pred_Ensemble', ...
    'Error', ...
    'Npred_Nexp'});

for fold = 1:K
    TestingPredictions.(sprintf('N_pred_Fold_%02d',fold)) = ...
        testPredByFold(:,fold);
end

Settings = table( ...
    K, ...
    fixedSeed, ...
    maxObjectiveEvaluations, ...
    learningRateRange(1), ...
    learningRateRange(2), ...
    numNeuronsRange(1), ...
    numNeuronsRange(2), ...
    hiddenLayersRange(1), ...
    hiddenLayersRange(2), ...
    numIter, ...
    lambda_data_total, ...
    lambda_reg, ...
    lossTol, ...
    checkEvery, ...
    minIterCheck, ...
    'VariableNames',{ ...
    'K', ...
    'FixedSeed', ...
    'MaxBayesianEvaluations', ...
    'LearningRate_Min', ...
    'LearningRate_Max', ...
    'Neurons_Min', ...
    'Neurons_Max', ...
    'HiddenLayers_Min', ...
    'HiddenLayers_Max', ...
    'MaxIterations', ...
    'LambdaData', ...
    'LambdaReg', ...
    'LossTolerance', ...
    'CheckEvery', ...
    'MinIterationCheck'});

writetable(BayesHistory,excelFile,'Sheet','BAYESIAN_HISTORY');
writetable(BestResult,excelFile,'Sheet','BEST_RESULT');
writetable(FoldMetrics,excelFile,'Sheet','BEST_FOLD_METRICS');
writetable(TestingPredictions,excelFile,'Sheet','INDEPENDENT_TESTING');
writetable(Settings,excelFile,'Sheet','SETTINGS');

%% 9) SAVE MAT FILE
save( ...
    matFile, ...
    'bayesResults', ...
    'bestLearningRate', ...
    'bestNumNeurons', ...
    'bestHiddenLayers', ...
    'bestCV_RMSE', ...
    'bestFoldModels', ...
    'bestFoldMuX', ...
    'bestFoldStdX', ...
    'bestFoldMuy', ...
    'bestFoldStdy', ...
    'bestFoldMetrics', ...
    'testPredByFold', ...
    'testPred', ...
    'testMetrics', ...
    'K', ...
    'fixedSeed', ...
    'lambda_data_total', ...
    'lambda_reg');

fprintf('\n====================================================\n');
fprintf('ANN Bayesian optimization completed.\n');
fprintf('Total time = %.2f h\n',toc(tTotal)/3600);
fprintf('Results: %s\n',excelFile);
fprintf('Command Window log: %s\n',commandWindowFile);
fprintf('====================================================\n');

%% ============================================================
%% LOCAL FUNCTIONS
%% ============================================================

function objective = annCVObjective( ...
    T, X, y, cv, K, fixedSeed, numIter, ...
    lambdaData, lambdaReg, lossTol, checkEvery, minIterCheck)

    learnRate = T.LearningRate;
    nNeuron = T.NumNeurons;
    nLayer = T.HiddenLayers;

    foldRMSE = nan(K,1);

    fprintf('\n----------------------------------------------------\n');
    fprintf( ...
        'Bayesian trial | HL=%d | Neurons=%d | LR=%.6e\n', ...
        nLayer,nNeuron,learnRate);

    for fold = 1:K

        idxTr = training(cv,fold);
        idxVa = test(cv,fold);

        Xtr = X(idxTr,:);
        ytr = y(idxTr);

        Xva = X(idxVa,:);
        yva = y(idxVa);

        % Normalization is based ONLY on the training portion of the fold
        muX = mean(Xtr,1);
        stdX = std(Xtr,0,1);
        stdX(stdX==0) = 1;

        muy = mean(ytr);
        stdy = std(ytr);

        if stdy==0
            stdy = 1;
        end

        xTr = dlarray(((Xtr-muX)./stdX)','CB');
        yTr = dlarray(((ytr-muy)./stdy)','CB');
        xVa = dlarray(((Xva-muX)./stdX)','CB');

        % Deterministic seed for comparison between trials
        rng( ...
            fixedSeed + ...
            1000*fold + ...
            round(1e7*learnRate) + ...
            10*nNeuron + ...
            nLayer, ...
            'twister');

        net = buildANN(nLayer,nNeuron);

        trailingAvg = [];
        trailingAvgSq = [];

        lossHistory = nan(numIter,1);

        for it = 1:numIter

            [loss,grad] = dlfeval( ...
                @lossFun, ...
                net, ...
                xTr, ...
                yTr, ...
                lambdaData, ...
                lambdaReg);

            [net,trailingAvg,trailingAvgSq] = adamupdate( ...
                net, ...
                grad, ...
                trailingAvg, ...
                trailingAvgSq, ...
                it, ...
                learnRate);

            lossHistory(it) = gather(extractdata(loss));

            if mod(it,checkEvery)==0 && it>=minIterCheck

                change = abs( ...
                    lossHistory(it) - ...
                    lossHistory(it-checkEvery));

                if change < lossTol
                    break
                end
            end
        end

        predVa = predictReal(net,xVa,muy,stdy);
        metrics = calcMetrics(yva,predVa);

        foldRMSE(fold) = metrics(3);

        fprintf( ...
            ' Fold %d/%d | RMSE=%.3f | R2=%.5f\n', ...
            fold,K,metrics(3),metrics(4));
    end

    objective = mean(foldRMSE);

    fprintf( ...
        ' Mean 5-fold validation RMSE = %.4f kN\n', ...
        objective);
end


function net = buildANN(nLayer,nNeuron)

    layers = featureInputLayer( ...
        5, ...
        'Normalization','none', ...
        'Name','input');

    for L = 1:nLayer

        layers = [
            layers
            fullyConnectedLayer( ...
                nNeuron, ...
                'Name',sprintf('fc%d',L))
            tanhLayer( ...
                'Name',sprintf('tanh%d',L))
        ]; %#ok<AGROW>
    end

    layers = [
        layers
        fullyConnectedLayer(1,'Name','output')
    ];

    net = dlnetwork(layerGraph(layers));
end


function [loss,grad] = lossFun(net,x,y,lambdaData,lambdaReg)

    yp = forward(net,x,'Outputs','output');

    dataLoss = mean((yp-y).^2,'all');

    reg = dlarray(0);

    vals = net.Learnables.Value;

    for q = 1:numel(vals)
        reg = reg + sum(vals{q}.^2,'all');
    end

    loss = lambdaData.*dataLoss + lambdaReg.*reg;

    grad = dlgradient(loss,net.Learnables);
end


function pred = predictReal(net,x,muy,stdy)

    p = forward(net,x,'Outputs','output');

    pred = gather(extractdata(p))'.*stdy + muy;
end


function m = calcMetrics(obs,pred)

    err = pred-obs;

    mae = mean(abs(err));
    mse = mean(err.^2);
    rmse = sqrt(mse);

    den = sum((obs-mean(obs)).^2);

    if den>0
        r2 = 1-sum(err.^2)/den;
    else
        r2 = NaN;
    end

    ratio = pred./obs;

    valid = isfinite(ratio);

    a20 = mean( ...
        ratio(valid)>=0.8 & ...
        ratio(valid)<=1.2)*100;

    meanRatio = mean(ratio(valid));
    sdRatio = std(ratio(valid));

    m = [
        mae, ...
        mse, ...
        rmse, ...
        r2, ...
        a20, ...
        meanRatio, ...
        sdRatio
    ];
end
