function GUI_CCFST_PINN
% ============================================================
% GUI for MINN-based CCFST Axial Capacity Prediction
% ============================================================

close all; clc;

%% ============================================================
% LOAD TRAINED MODEL
%% ============================================================

global net muX stdX muy stdy RMSE R2

S = load('cfst_model_N_S_MINN_ver2.mat');

net  = S.net;
muX  = S.muX;
stdX = S.stdX;
muy  = S.muy;
stdy = S.stdy;

if isfield(S,'RMSE')
    RMSE = S.RMSE;
else
    RMSE = NaN;
end

if isfield(S,'R2')
    R2 = S.R2;
else
    R2 = NaN;
end

%% ============================================================
% MAIN FIGURE
%% ============================================================

fig = figure(...
    'Name','CCFST MINN - Axial Capacity Predictor',...
    'Position',[100 40 1400 850],...
    'Color',[0.94 0.94 0.94],...
    'NumberTitle','off',...
    'MenuBar','none',...
    'Resize','off');

%% ============================================================
% INPUT PANEL
%% ============================================================

pInput = uipanel(fig,...
    'Title','Input Parameters',...
    'FontSize',18,...
    'FontWeight','bold',...
    'BackgroundColor','white',...
    'Position',[0.03 0.08 0.46 0.86]);

names = {'Outer Diameter, D', ...
         'Tube Thickness, t', ...
         'Steel Yield Strength, fy', ...
         'Concrete Strength, fc''', ...
         'Column Length, L'};

units = {'mm','mm','MPa','MPa','mm'};

defaults = [300 6 345 40 900];

fcTypeList = {...
    'fcyl,150x300', ...
    'fcyl,100x200', ...
    'fcyl,250x500', ...
    'fcu,100', ...
    'fcu,150', ...
    'fcu,200', ...
    'fcu,300'};

fcFactorList = [1.00 0.97 1.05 0.80 0.80 0.83 0.90];

editBox = gobjects(1,5);

startY   = 625;
spacingY = 105;

for i = 1:5

    yPos = startY - (i-1)*spacingY;

    % Move Column Length downward
    if i == 5
        yPos = yPos - 25;
    end

    %% ---------- Variable Name ----------
    uicontrol(pInput,...
        'Style','text',...
        'String',names{i},...
        'HorizontalAlignment','left',...
        'FontSize',15,...
        'BackgroundColor','white',...
        'Position',[30 yPos 260 32]);

    %% ---------- Input Box ----------
    editBox(i) = uicontrol(pInput,...
        'Style','edit',...
        'String',num2str(defaults(i)),...
        'BackgroundColor',[0.88 0.95 1.00],...
        'FontSize',17,...
        'FontWeight','bold',...
        'Position',[320 yPos-2 120 40]);

    %% ---------- Unit ----------
    uicontrol(pInput,...
        'Style','text',...
        'String',units{i},...
        'HorizontalAlignment','left',...
        'FontSize',15,...
        'BackgroundColor','white',...
        'Position',[460 yPos 80 32]);

    %% ---------- Concrete Type Below fc' ----------
    if i == 4

        uicontrol(pInput,...
            'Style','text',...
            'String','Concrete Type',...
            'HorizontalAlignment','left',...
            'FontSize',13,...
            'BackgroundColor','white',...
            'Position',[320 yPos-45 160 28]);

        popup_fcType = uicontrol(pInput,...
            'Style','popupmenu',...
            'String',fcTypeList,...
            'FontSize',12,...
            'BackgroundColor',[0.88 0.95 1.00],...
            'Position',[320 yPos-75 220 35]);

    end

end

%% ============================================================
% CONVERTED CONCRETE CYLINDER STRENGTH
%% ============================================================

uicontrol(pInput,...
    'Style','text',...
    'String','Converted Concrete Cylinder Strength',...
    'HorizontalAlignment','left',...
    'FontSize',12,...
    'BackgroundColor','white',...
    'Position',[30 95 420 32]);

txt_fc_conv = uicontrol(pInput,...
    'Style','edit',...
    'String','---',...
    'FontSize',15,...
    'FontWeight','bold',...
    'BackgroundColor',[0.94 0.94 0.94],...
    'Enable','inactive',...
    'HorizontalAlignment','center',...
    'Position',[320 90 120 40]);

uicontrol(pInput,...
    'Style','text',...
    'String','MPa',...
    'HorizontalAlignment','left',...
    'FontSize',15,...
    'BackgroundColor','white',...
    'Position',[460 95 60 30]);

%% ============================================================
% CALCULATED L/D
%% ============================================================

uicontrol(pInput,...
    'Style','text',...
    'String','Calculated L/D',...
    'HorizontalAlignment','left',...
    'FontSize',15,...
    'BackgroundColor','white',...
    'Position',[30 40 260 32]);

txt_LD = uicontrol(pInput,...
    'Style','edit',...
    'String','---',...
    'FontSize',16,...
    'FontWeight','bold',...
    'BackgroundColor',[0.94 0.94 0.94],...
    'Enable','inactive',...
    'Position',[320 35 120 40]);

%% ============================================================
% OUTPUT PANEL
%% ============================================================

pOut = uipanel(fig,...
    'Title','Prediction Results of the Proposed CCFST-MINN Model',...
    'FontSize',17,...
    'FontWeight','bold',...
    'BackgroundColor','white',...
    'Position',[0.52 0.35 0.45 0.59]);

%% ---------- Nu ----------
uicontrol(pOut,...
    'Style','text',...
    'String','Predicted Axial Capacity, Nu',...
    'HorizontalAlignment','left',...
    'FontSize',16,...
    'BackgroundColor','white',...
    'Position',[40 300 300 40]);

txt_Nu = uicontrol(pOut,...
    'Style','edit',...
    'String','---',...
    'FontSize',24,...
    'FontWeight','bold',...
    'BackgroundColor',[0.90 1.00 0.90],...
    'Position',[360 295 160 55]);

uicontrol(pOut,...
    'Style','text',...
    'String','kN',...
    'FontSize',18,...
    'BackgroundColor','white',...
    'Position',[540 305 60 40]);

%% ---------- L/r ----------
uicontrol(pOut,...
    'Style','text',...
    'String','Calculated Slenderness Ratio, L/r',...
    'HorizontalAlignment','left',...
    'FontSize',15,...
    'BackgroundColor','white',...
    'Position',[40 210 320 35]);

txt_Lr = uicontrol(pOut,...
    'Style','edit',...
    'String','---',...
    'FontSize',18,...
    'FontWeight','bold',...
    'BackgroundColor',[0.94 0.94 0.94],...
    'Enable','inactive',...
    'Position',[380 205 140 45]);

%% ---------- Limitation ----------
uicontrol(pOut,...
    'Style','text',...
    'String','Limitation Status',...
    'HorizontalAlignment','left',...
    'FontSize',15,...
    'BackgroundColor','white',...
    'Position',[40 120 220 35]);

txt_limit = uicontrol(pOut,...
    'Style','text',...
    'String','---',...
    'HorizontalAlignment','left',...
    'FontSize',15,...
    'FontWeight','bold',...
    'BackgroundColor','white',...
    'Position',[260 120 380 35]);

%% ============================================================
% BUTTONS
%% ============================================================

btnW = 170;
btnH = 55;
yBtn = 160;

uicontrol(fig,...
    'Style','pushbutton',...
    'String','Predict',...
    'FontSize',16,...
    'FontWeight','bold',...
    'Position',[760 yBtn btnW btnH],...
    'Callback',@predict_callback);

uicontrol(fig,...
    'Style','pushbutton',...
    'String','Clear',...
    'FontSize',16,...
    'FontWeight','bold',...
    'Position',[960 yBtn btnW btnH],...
    'Callback',@clear_callback);

uicontrol(fig,...
    'Style','pushbutton',...
    'String','Save',...
    'FontSize',16,...
    'FontWeight','bold',...
    'Position',[1160 yBtn btnW btnH],...
    'Callback',@save_callback);

uicontrol(fig,...
    'Style','pushbutton',...
    'String','Exit',...
    'FontSize',16,...
    'FontWeight','bold',...
    'Position',[960 80 btnW btnH],...
    'Callback',@(src,evt) close(fig));

%% ============================================================
% CALLBACK: PREDICT
%% ============================================================

function predict_callback(~,~)

    vals = zeros(1,5);

    for k = 1:5
        vals(k) = str2double(editBox(k).String);
    end

    %% ---------- Check NaN ----------
    if any(isnan(vals))

        errordlg(...
            'Please enter numeric values for all inputs.',...
            'Input Error');

        return;
    end

    %% ---------- Inputs ----------
    D        = vals(1);
    t        = vals(2);
    fy       = vals(3);
    fc_input = vals(4);
    L        = vals(5);

    %% ---------- Check positive ----------
    if D <= 0 || t <= 0 || fy <= 0 || fc_input <= 0 || L <= 0

        errordlg(...
            'All input values must be greater than zero.',...
            'Input Error');

        return;
    end

    %% ========================================================
    % CONVERT fc'
    %% ========================================================

    idx_fcType = popup_fcType.Value;
    fc_factor  = fcFactorList(idx_fcType);

    fc = fc_input * fc_factor;

    txt_fc_conv.String = sprintf('%.2f',fc);

    %% ========================================================
    % CALCULATE L/D
    %% ========================================================

    L_D = L / D;

    txt_LD.String = sprintf('%.3f',L_D);

    %% ========================================================
    % CHECK TRAINING RANGE
    %% ========================================================

    rangeWarning = {};

    if D < 47.28 || D > 1020.00
        rangeWarning{end+1} = ...
            'D is outside the training range';
    end

    if t < 0.52 || t > 16.53
        rangeWarning{end+1} = ...
            't is outside the training range';
    end

    if fy < 185.70 || fy > 853.00
        rangeWarning{end+1} = ...
            'fy is outside the training range';
    end

    if fc < 5.51 || fc > 179.55
        rangeWarning{end+1} = ...
            'fc'' is outside the training range';
    end

    if L_D < 0.81 || L_D > 7.46
        rangeWarning{end+1} = ...
            'L/D is outside the training range';
    end

    if ~isempty(rangeWarning)

        warningMessage = sprintf([...
            'Input value is outside the training data range.\n\n' ...
            'Prediction accuracy may be reduced.\n\n' ...
            '%s'],...
            strjoin(rangeWarning,newline));

        warndlg(warningMessage,...
                'Training Data Range Warning');

    end

    %% ========================================================
    % CALCULATE L/r
    %% ========================================================

    r = D / 4;

    L_r = L / r;

    txt_Lr.String = sprintf('%.3f',L_r);

    %% ========================================================
    % CHECK LIMITATION
    %% ========================================================

    if L_r > 22

        txt_limit.String = ...
            'Out of limitation (slender column)';

        txt_limit.ForegroundColor = [1 0 0];

        txt_Nu.String = '---';

        warndlg(...
            'Out of limitation: L/r > 22',...
            'Slender Column Warning');

        return;

    else

        txt_limit.String = ...
            'Within limitation (stub column)';

        txt_limit.ForegroundColor = [0 0.45 0];

    end

    %% ========================================================
    % INPUT VECTOR
    %% ========================================================

    X = [D t fy fc L_D];

    %% ========================================================
    % NORMALIZATION
    %% ========================================================

    Xn = (X - muX) ./ stdX;

    xdl = dlarray(Xn','CB');

    %% ========================================================
    % PREDICTION
    %% ========================================================

    y_norm = forward(net,...
                     xdl,...
                     'Outputs','output');

    y_norm = extractdata(y_norm);

    Nu_pred = y_norm * stdy + muy;

    %% ========================================================
    % DISPLAY
    %% ========================================================

    txt_Nu.String = sprintf('%.2f',Nu_pred);

end

%% ============================================================
% CALLBACK: CLEAR
%% ============================================================

function clear_callback(~,~)

    for k = 1:5
        editBox(k).String = '';
    end

    popup_fcType.Value = 1;

    txt_Nu.String      = '---';
    txt_LD.String      = '---';
    txt_Lr.String      = '---';
    txt_fc_conv.String = '---';
    txt_limit.String   = '---';

    txt_limit.ForegroundColor = [0 0 0];

end

%% ============================================================
% CALLBACK: SAVE
%% ============================================================

function save_callback(~,~)

    prompt = {'Project Name:'};

    dlgtitle = 'Save Prediction';

    answer = inputdlg(prompt,...
                      dlgtitle,...
                      [1 40],...
                      {'CCFST_Project'});

    if isempty(answer)
        return;
    end

    pname = answer{1};

    fname = [pname '_CCFST_MINN_prediction.txt'];
    % ========================================================
% Re-calculate converted concrete strength for saving
% ========================================================
    fc_input_save = str2double(editBox(4).String);

    if isnan(fc_input_save)
    fc_save = NaN;
     else
    idx_fcType_save = popup_fcType.Value;
    fc_factor_save  = fcFactorList(idx_fcType_save);
    fc_save = fc_input_save * fc_factor_save;
    end

    fid = fopen(fname,'w');

    fprintf(fid,'====================================\n');
    fprintf(fid,'CCFST MINN Prediction\n');
    fprintf(fid,'====================================\n\n');

    fprintf(fid,'Input Parameters\n');
    fprintf(fid,'------------------------------------\n');

    for k = 1:5

        fprintf(fid,...
            '%s = %s %s\n',...
            names{k},...
            editBox(k).String,...
            units{k});

    end

    fprintf(fid,...
    'Converted Concrete Cylinder Strength = %.2f MPa\n',...
     fc_save);

    fprintf(fid,...
        'Calculated L/D = %s\n',...
        txt_LD.String);

    fprintf(fid,...
        'Calculated L/r = %s\n',...
        txt_Lr.String);

    fprintf(fid,...
        'Limitation Status = %s\n',...
        txt_limit.String);

    fprintf(fid,...
        '\n------------------------------------\n');

    fprintf(fid,...
        'Predicted Nu = %s kN\n',...
        txt_Nu.String);

    if ~isnan(RMSE)

        fprintf(fid,...
            'Model RMSE = %.4f\n',...
            RMSE);

    end

    if ~isnan(R2)

        fprintf(fid,...
            'Model R2 = %.4f\n',...
            R2);

    end

    fclose(fid);

    msgbox(sprintf('Saved to %s',fname),...
           'Saved');

end

end