clc;
clear;
close all;

%% ===================== Select Excel file =====================
[fileName, filePath] = uigetfile('*.xlsx', 'Select Excel file');

if isequal(fileName,0)
    error('No Excel file selected');
end

fullFile = fullfile(filePath, fileName);

%% ===================== Read Excel sheets =====================
trainData = readtable(fullFile, ...
    'Sheet','training', ...
    'VariableNamingRule','preserve');

testData = readtable(fullFile, ...
    'Sheet','testing', ...
    'VariableNamingRule','preserve');

%% ===================== Fix column names =====================
trainCols = trainData.Properties.VariableNames;
testData.Properties.VariableNames = trainCols;

%% ===================== Actual values =====================
% Column 1 = Real Nu
yTrain = trainData{:,1};
yTest  = testData{:,1};

%% ===================== Algorithm names =====================
algorithms = trainCols(2:end);

%% ===================== Output folder =====================
outDir = 'Accuracy_indicator';

if ~exist(outDir,'dir')
    mkdir(outDir);
end

%% ===================== Zoom range =====================
zoomRange = [-200 5000];

%% ===================== Loop each algorithm =====================
for a = 1:length(algorithms)

    alg = algorithms{a};

    %% ===================== Prediction =====================
    yPredTrain = trainData{:,alg};
    yPredTest  = testData{:,alg};

    %% ===================== Metrics =====================
    metTrain = calMetrics(yTrain, yPredTrain);
    metTest  = calMetrics(yTest,  yPredTest);

    %% ===================== Number of data =====================
    nTrain = sum(~isnan(yTrain) & ~isnan(yPredTrain));
    nTest  = sum(~isnan(yTest)  & ~isnan(yPredTest));

    %% ===================== Axis limit =====================
    allVal = [yTrain; yTest; yPredTrain; yPredTest];

    maxVal = max(allVal, [], 'omitnan');

    limMax = ceil(maxVal/1000)*1000;

    xLineMain = linspace(-200, limMax, 500);

    xLineZoom = linspace(zoomRange(1), zoomRange(2), 200);

    %% ===================== Main figure =====================
    fig = figure('Color','w', ...
        'Position',[100 100 750 680]);

    mainAx = axes(fig);

    hold(mainAx,'on');

    %% ===================== TRAIN =====================
    scatter(mainAx,...
        yTrain,...
        yPredTrain,...
        40,...
        's',...
        'LineWidth',1.2,...
        'MarkerEdgeColor',[0 0.4470 0.7410]);

    %% ===================== TEST =====================
    scatter(mainAx,...
        yTest,...
        yPredTest,...
        45,...
        '^',...
        'LineWidth',1.2,...
        'MarkerEdgeColor',[1 0 0]);

    %% ===================== y = x =====================
    plot(mainAx,...
        xLineMain,...
        xLineMain,...
        'k-',...
        'LineWidth',1.5);

    %% ===================== +20% =====================
    plot(mainAx,...
        xLineMain,...
        1.2.*xLineMain,...
        'k--',...
        'LineWidth',1.2);

    %% ===================== -20% =====================
    plot(mainAx,...
        xLineMain,...
        0.8.*xLineMain,...
        'k--',...
        'LineWidth',1.2);

    %% ===================== Zoom rectangle =====================
    rectangle(mainAx,...
        'Position',[ ...
        zoomRange(1), ...
        zoomRange(1), ...
        zoomRange(2)-zoomRange(1), ...
        zoomRange(2)-zoomRange(1)],...
        'EdgeColor','k',...
        'LineStyle','--',...
        'LineWidth',1.2);

    %% ===================== Metrics text =====================
    txt = sprintf([ ...
        'Train (n = %d)\n' ...
        'R^2 = %.2f%%\n' ...
        'RMSE = %.2f\n' ...
        'MSE = %.2f\n' ...
        'MAE = %.2f\n' ...
        'A20 = %.2f%%\n\n' ...
        'Test (n = %d)\n' ...
        'R^2 = %.2f%%\n' ...
        'RMSE = %.2f\n' ...
        'MSE = %.2f\n' ...
        'MAE = %.2f\n' ...
        'A20 = %.2f%%'], ...
        nTrain,...
        metTrain.R2*100,...
        metTrain.RMSE,...
        metTrain.MSE,...
        metTrain.MAE,...
        metTrain.A20*100,...
        nTest,...
        metTest.R2*100,...
        metTest.RMSE,...
        metTest.MSE,...
        metTest.MAE,...
        metTest.A20*100);

    text(mainAx,...
        0.05*limMax,...
        0.95*limMax,...
        txt,...
        'FontName','Times New Roman',...
        'FontSize',14,...
        'VerticalAlignment','top',...
        'BackgroundColor','white',...
        'EdgeColor',[0.5 0.5 0.5]);

    %% ===================== Main format =====================
    title(mainAx,...
        alg,...
        'FontName','Times New Roman',...
        'FontSize',50,...
        'FontWeight','bold');

    xlabel(mainAx,...
        'Nu (Real value, kN)',...
        'FontName','Times New Roman',...
        'FontSize',22);

    ylabel(mainAx,...
        'Nu (Predicted value, kN)',...
        'FontName','Times New Roman',...
        'FontSize',22);

    legend(mainAx,...
        {'Train','Test','y = x','+20%','-20%'},...
        'Location','northeast',...
        'FontName','Times New Roman',...
        'FontSize',14);

    xlim(mainAx,[-200 limMax]);
    ylim(mainAx,[-200 limMax]);

    axis(mainAx,'square');

    grid(mainAx,'off');
    box(mainAx,'on');

    set(mainAx,...
        'FontName','Times New Roman',...
        'FontSize',12,...
        'LineWidth',1.2);

    %% ===================== ZOOM INSET =====================
    insetAx = axes('Position',[0.56 0.18 0.34 0.34]);

    hold(insetAx,'on');

    %% ===================== Train inset =====================
    scatter(insetAx,...
        yTrain,...
        yPredTrain,...
        20,...
        's',...
        'LineWidth',1.0,...
        'MarkerEdgeColor',[0 0.4470 0.7410]);

    %% ===================== Test inset =====================
    scatter(insetAx,...
        yTest,...
        yPredTest,...
        24,...
        '^',...
        'LineWidth',1.0,...
        'MarkerEdgeColor',[1 0 0]);

    %% ===================== y = x =====================
    plot(insetAx,...
        xLineZoom,...
        xLineZoom,...
        'k-',...
        'LineWidth',1.0);

    %% ===================== +20% =====================
    plot(insetAx,...
        xLineZoom,...
        1.2.*xLineZoom,...
        'k--',...
        'LineWidth',0.8);

    %% ===================== -20% =====================
    plot(insetAx,...
        xLineZoom,...
        0.8.*xLineZoom,...
        'k--',...
        'LineWidth',0.8);

    %% ===================== Inset format =====================
    xlim(insetAx,zoomRange);
    ylim(insetAx,zoomRange);

    axis(insetAx,'square');

    grid(insetAx,'off');
    box(insetAx,'on');

    set(insetAx,...
        'FontName','Times New Roman',...
        'FontSize',10,...
        'LineWidth',1);

    title(insetAx,...
        'Zoom: -200 to 5000 kN',...
        'FontName','Times New Roman',...
        'FontSize',12,...
        'FontWeight','bold');

    %% ===================== Export =====================
    safeName = regexprep(alg,'[^a-zA-Z0-9_]','_');

    exportgraphics(fig,...
        fullfile(outDir,[safeName '_Parity_Hollow.png']),...
        'Resolution',1200);

    exportgraphics(fig,...
        fullfile(outDir,[safeName '_Parity_Hollow.tiff']),...
        'Resolution',1200);

    close(fig);

end

disp('Finished: all parity plots exported.');

%% =====================================================
%% ===================== FUNCTION ======================
%% =====================================================

function met = calMetrics(yTrue, yPred)

    valid = ~isnan(yTrue) & ~isnan(yPred);

    yTrue = yTrue(valid);
    yPred = yPred(valid);

    err = yPred - yTrue;

    %% ===================== MAE =====================
    met.MAE = mean(abs(err));

    %% ===================== MSE =====================
    met.MSE = mean(err.^2);

    %% ===================== RMSE =====================
    met.RMSE = sqrt(met.MSE);

    %% ===================== R2 =====================
    SSres = sum((yTrue - yPred).^2);

    SStot = sum((yTrue - mean(yTrue)).^2);

    met.R2 = 1 - SSres/SStot;

    %% ===================== A20 =====================
    ratio = yPred ./ yTrue;

    met.A20 = mean(ratio >= 0.8 & ratio <= 1.2);

end